
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkwfucgtpmdefexrbfjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrd2Z1Y2d0cG1kZWZleHJiZmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDc2MTQsImV4cCI6MjA2MDI4MzYxNH0.rxmDQTo47QJ9CbmlzH2hbSgKP1mTa69XhWx3BMZSpj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Initialize the storage bucket
export const initializeStorageBucket = async () => {
  try {
    const { data, error } = await supabase.functions.invoke('create-storage-bucket');
    
    if (error) {
      console.error('Error initializing storage bucket:', error);
      return { success: false, error };
    }
    
    console.log('Storage bucket initialized:', data);
    return { success: true, data };
  } catch (error) {
    console.error('Failed to initialize storage bucket:', error);
    return { success: false, error };
  }
};
